name: 'Get $ Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  work-dir:
    description: 'The directory where script should be executed.'
    required: false
    default: ./
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      working-directory: ${{ inputs.work-dir }}
      run: npm ci
      shell: bash